import jsPDF from 'jspdf';
import { PurchaseOrder } from '@/types/purchaseOrder';
import { InvoiceSettings } from '@/types/sale';
import { format } from 'date-fns';

export async function generatePurchaseOrderPDF(order: PurchaseOrder, settings?: InvoiceSettings) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const formatDate = (date: Date) => {
    return format(date, 'MMMM d, yyyy');
  };

  // Add logo if available
  if (settings?.logoUrl) {
    try {
      const img = await loadImage(settings.logoUrl);
      const imgWidth = 40;
      const imgHeight = (img.height / img.width) * imgWidth;
      doc.addImage(img, 'PNG', 20, y, imgWidth, Math.min(imgHeight, 40));
      y += Math.min(imgHeight, 40) + 10;
    } catch (e) {
      console.error('Failed to load logo:', e);
    }
  }

  // Business Info (right side)
  if (settings?.businessName || settings?.businessAddress || settings?.businessPhone || settings?.businessEmail) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    let businessY = 20;
    
    if (settings.businessName) {
      doc.setFont('helvetica', 'bold');
      doc.text(settings.businessName, pageWidth - 20, businessY, { align: 'right' });
      businessY += 5;
      doc.setFont('helvetica', 'normal');
    }
    if (settings.businessAddress) {
      const addressLines = settings.businessAddress.split('\n');
      addressLines.forEach((line) => {
        doc.text(line, pageWidth - 20, businessY, { align: 'right' });
        businessY += 5;
      });
    }
    if (settings.businessPhone) {
      doc.text(settings.businessPhone, pageWidth - 20, businessY, { align: 'right' });
      businessY += 5;
    }
    if (settings.businessEmail) {
      doc.text(settings.businessEmail, pageWidth - 20, businessY, { align: 'right' });
    }
    
    y = Math.max(y, businessY + 10);
  }

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('PURCHASE ORDER', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // PO Info
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`PO Number: PO-${order.id.slice(0, 8).toUpperCase()}`, 20, y);
  doc.text(`Order Date: ${formatDate(order.orderedAt)}`, pageWidth - 20, y, {
    align: 'right',
  });
  y += 7;
  doc.text(`Status: ${order.status.toUpperCase()}`, 20, y);
  if (order.receivedAt) {
    doc.text(`Received: ${formatDate(order.receivedAt)}`, pageWidth - 20, y, {
      align: 'right',
    });
  }
  y += 15;

  // Vendor Info
  if (order.vendorName) {
    doc.setFont('helvetica', 'bold');
    doc.text('Vendor:', 20, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.text(order.vendorName, 20, y);
    y += 10;
  }

  // Items Table Header
  doc.setFillColor(240, 240, 240);
  doc.rect(20, y - 4, pageWidth - 40, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text('Item', 22, y);
  doc.text('SKU', 100, y);
  doc.text('Quantity', pageWidth - 22, y, { align: 'right' });
  y += 10;

  // Items
  doc.setFont('helvetica', 'normal');
  order.items.forEach((item) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }
    
    const itemName =
      item.itemName.length > 40
        ? item.itemName.substring(0, 40) + '...'
        : item.itemName;
    doc.text(itemName, 22, y);
    doc.text(item.sku, 100, y);
    doc.text(item.quantity.toString(), pageWidth - 22, y, { align: 'right' });
    y += 7;
  });

  // Line
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // Total Quantity
  const totalQuantity = order.items.reduce((sum, item) => sum + item.quantity, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Total Items:', pageWidth - 70, y);
  doc.text(totalQuantity.toString(), pageWidth - 22, y, { align: 'right' });

  // Notes
  if (order.notes) {
    y += 20;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Notes:', 20, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    
    const splitNotes = doc.splitTextToSize(order.notes, pageWidth - 40);
    doc.text(splitNotes, 20, y);
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Inventory Management System', pageWidth / 2, footerY, {
    align: 'center',
  });

  // Save the PDF
  doc.save(`PO-${order.id.slice(0, 8).toUpperCase()}.pdf`);
}

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = url;
  });
}
