-- Extend storefront_settings with comprehensive customization options
ALTER TABLE public.storefront_settings
ADD COLUMN header_banner_url text,
ADD COLUMN background_color text DEFAULT '#ffffff',
ADD COLUMN background_image_url text,
ADD COLUMN background_overlay_opacity integer DEFAULT 0 CHECK (background_overlay_opacity >= 0 AND background_overlay_opacity <= 100),
ADD COLUMN background_blur integer DEFAULT 0 CHECK (background_blur >= 0 AND background_blur <= 20),
ADD COLUMN primary_color text DEFAULT '#000000',
ADD COLUMN secondary_color text DEFAULT '#6b7280',
ADD COLUMN accent_color text DEFAULT '#3b82f6',
ADD COLUMN button_color text DEFAULT '#3b82f6',
ADD COLUMN text_color text DEFAULT '#000000',
ADD COLUMN product_card_spacing text DEFAULT 'normal',
ADD COLUMN product_image_shape text DEFAULT 'square',
ADD COLUMN grid_columns integer DEFAULT 4 CHECK (grid_columns >= 2 AND grid_columns <= 6),
ADD COLUMN show_featured_section boolean DEFAULT false,
ADD COLUMN welcome_message text,
ADD COLUMN product_card_bg_color text DEFAULT '#ffffff',
ADD COLUMN show_prices boolean DEFAULT true,
ADD COLUMN enable_search boolean DEFAULT true,
ADD COLUMN enable_categories boolean DEFAULT true,
ADD COLUMN contact_button_text text,
ADD COLUMN contact_button_url text,
ADD COLUMN link_button_text text,
ADD COLUMN link_button_url text;